site_name: AIML_Learning

nav:
  - Home: index.md
  - AI/ML:
      - Fundamentals: AIML/Fundamentals.md
      - Harness Engineering: AIML/01HarnessEngineering.md
      - Memory Management: AIML/02AI_Agent_Memory.md
  - Interview Questions:
      - Fundamentals: AI_Interview/InterviewQuestion.md

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
#    - toc.integrate
#    - header.autohide
extra_css:
  - css/custom.css